import type { ResourcesToLoad } from "@/core/asset_loader";

// DEFINED MESSAGES
export enum Msg {
    /** Broadcasts when the project has finished loading. */
    START = "START",
    /** Broadcasts on each screen refresh. */
    TICK = "TICK",

    INIT_SHOW_CAUTION = "SHOW_CAUTION",
    CLOSE_CAUTION = "HIDE_CAUTION",
    SHOW_MENU = "SHOW_MENU",
    SHOW_MENU2 = "SHOW_MENU2",
    HIDE_MENU = "HIDE_MENU",

    SHOW_INSTRUCTIONS = "SHOW_INSTRUCTIONS",
    HIDE_INSTRUCTIONS = "HIDE_INSTRUCTIONS",

    INIT_GAME = "INIT_GAME",

    START_GAME = "START_GAME",
    NEXT_QUESTION = "NEXT_QUESTION",

    TICK_MENU_CLICK = "TICK_MENU_CLICK",
    TICK_MENU_LOGIC = "TICK_MENU_LOGIC",

    TICK_GAME_CLICK = "TICK_GAME_CLICK",
    TICK_GAME_LOGIC = "TICK_GAME_LOGIC",
    TICK_GAME_BOMB = "TICK_GAME_BOMB",

    SHOW_GAME_OVER = "SHOW_GAME_OVER",
    
    PLAY_CLICKED = "PLAY_CLICKED",
    PLAY_AGAIN_CLICKED = "PLAY_AGAIN_CLICKED",
    GAME_COMPLETE = "GAME_COMPLETE",
}

export const settings: Readonly<{
    SCREEN_WIDTH: number,
    SCREEN_HEIGHT: number,
    MAX_LAYERS?: number
}>
= Object.freeze({
    SCREEN_WIDTH: 480,
    SCREEN_HEIGHT: 360,
    MAX_LAYERS: 1
} as const)

export function getResourcesToLoad(): ResourcesToLoad {
    return {
        images: {
            "36:1a": "assets/36/boy.png",
            "36:1b": "assets/36/index_pointing_up.png",
            "36:2a": "assets/36/red_envelope.png",
            "36:2b": "assets/36/airplane.png",
            "36:3a": "assets/36/three.png",
            "36:3b": "assets/36/pig_face.png",
            "36:4a": "assets/36/coin.png",
            "36:4b": "assets/36/tropical_fish.png",

            "40:screen": "assets/40/screen.png",
            "40:red_flash": "assets/40/red_flash.png",
            "40:orange_flash": "assets/40/orange_flash.png",
            "40:yellow_flash": "assets/40/yellow_flash.png",
            "40:green_flash": "assets/40/green_flash.png",
            "40:light_blue_flash": "assets/40/light_blue_flash.png",
            "40:blue_flash": "assets/40/blue_flash.png",
            "40:purple_flash": "assets/40/purple_flash.png",
            "40:white_flash": "assets/40/white_flash.png",

            "44:maze_collision": "assets/44/maze_collision.png",
            "44:maze_spinner_collision": "assets/44/maze_spinner_collision.png",

            "effect-paint": "assets/game/effect-paint.png",
        },
        svg: {
            "menus:caution": "assets/menus/caution.svg",
            "menus:instructions-1": "assets/menus/instructions-1.svg",
            "menus:instructions-2": "assets/menus/instructions-2.svg",
            "menus:instructions-2-light": "assets/menus/instructions-2-light.svg",
            "menus:game_over": "assets/menus/game_over.svg",
            "menus:game_over-light": "assets/menus/game_over-light.svg",

            "title-1": "assets/menus/title-1.svg",
            "title-2": "assets/menus/title-2.svg",
            "title-3": "assets/menus/title-3.svg",

            "menus:button-continue": "assets/menus/button-continue.svg",
            "menus:button-continue-p": "assets/menus/button-continue-p.svg",
            "menus:button-play": "assets/menus/button-play.svg",
            "menus:button-play-p": "assets/menus/button-play-p.svg",
            "menus:button-back": "assets/menus/button-back.svg",
            "menus:button-back-p": "assets/menus/button-back-p.svg",
            "menus:button-how_to_play": "assets/menus/button-how_to_play.svg",
            "menus:button-how_to_play-p": "assets/menus/button-how_to_play-p.svg",
            "menus:button-play_part": "assets/menus/button-play_part.svg",
            "menus:button-play_part-p": "assets/menus/button-play_part-p.svg",
            
            "menus:button-play_again": "assets/menus/button-play_again.svg",
            "menus:button-play_again-p": "assets/menus/button-play_again-p.svg",

            "background_decoration-f1": "assets/game/background_decoration-f1.svg",
            "background_decoration-f2": "assets/game/background_decoration-f2.svg",

            "button-choice": "assets/game/button-choice.svg",
            "button-choice-p": "assets/game/button-choice-p.svg",

            "lives-text": "assets/game/lives-text.svg",
            "lives-1": "assets/game/lives-1.svg",
            "lives-2": "assets/game/lives-2.svg",
            "lives-3": "assets/game/lives-3.svg",
            "lives-4": "assets/game/lives-4.svg",
            "lives-5": "assets/game/lives-5.svg",

            "bomb-f1": "assets/game/bomb-f1.svg",
            "bomb-f2": "assets/game/bomb-f2.svg",
            "bomb-f3": "assets/game/bomb-f3.svg",
            "bomb-f4": "assets/game/bomb-f4.svg",
            "time_bomb-0": "assets/game/time_bomb-0.svg",
            "time_bomb-1": "assets/game/time_bomb-1.svg",
            "time_bomb-2": "assets/game/time_bomb-2.svg",
            "time_bomb-3": "assets/game/time_bomb-3.svg",
            "time_bomb-4": "assets/game/time_bomb-4.svg",
            "time_bomb-5": "assets/game/time_bomb-5.svg",
            "time_bomb-6": "assets/game/time_bomb-6.svg",
            "time_bomb-7": "assets/game/time_bomb-7.svg",
            "time_bomb-8": "assets/game/time_bomb-8.svg",
            "time_bomb-9": "assets/game/time_bomb-9.svg",
            "time_bomb-10": "assets/game/time_bomb-10.svg",
            "time_bomb-11": "assets/game/time_bomb-11.svg",
            "time_bomb-12": "assets/game/time_bomb-12.svg",
            "time_bomb-13": "assets/game/time_bomb-13.svg",
            "time_bomb-14": "assets/game/time_bomb-14.svg",
            "time_bomb-15": "assets/game/time_bomb-15.svg",

            "question-31": "assets/questions/31.svg",
            "question-32": "assets/questions/32.svg",
            "question-33": "assets/questions/33.svg",
            "question-34": "assets/questions/34.svg",
            "question-35": "assets/questions/35.svg",
            "question-36": "assets/questions/36.svg",
            "question-37": "assets/questions/37.svg",
            "question-38": "assets/questions/38.svg",
            "question-39": "assets/questions/39.svg",
            "question-41": "assets/questions/41.svg",
            "question-42": "assets/questions/42.svg",
            "question-43": "assets/questions/43.svg",
            "question-45": "assets/questions/45.svg",
            "question-46": "assets/questions/46.svg",
            "question-47": "assets/questions/47.svg",
            "question-48": "assets/questions/48.svg",
            "question-49": "assets/questions/49.svg",
            "question-51": "assets/questions/51.svg",
            "question-52": "assets/questions/52.svg",
            "question-53": "assets/questions/53.svg",
            "question-54": "assets/questions/54.svg",
            "question-55-q": "assets/questions/55-q.svg",
            "question-56": "assets/questions/56.svg",
            "question-56-q": "assets/questions/56-q.svg",
            "question-57": "assets/questions/57.svg",
            "question-58": "assets/questions/58.svg",
            "question-59": "assets/questions/59.svg",
            "question-61": "assets/questions/61.svg",
            "question-62": "assets/questions/62.svg",
            "question-62-a": "assets/questions/62-a.svg",
            "question-63": "assets/questions/63.svg",
            "question-64": "assets/questions/64.svg",
            "question-66": "assets/questions/66.svg",
            "question-67": "assets/questions/67.svg",
            "question-69": "assets/questions/69.svg",

            "question_number-circle": "assets/question_numbers/circle.svg",
            "question_number-31": "assets/question_numbers/31.svg",
            "question_number-32": "assets/question_numbers/32.svg",
            "question_number-33": "assets/question_numbers/33.svg",
            "question_number-34": "assets/question_numbers/34.svg",
            "question_number-35": "assets/question_numbers/35.svg",
            "question_number-36": "assets/question_numbers/36.svg",
            "question_number-37": "assets/question_numbers/37.svg",
            "question_number-38": "assets/question_numbers/38.svg",
            "question_number-39": "assets/question_numbers/39.svg",
            "question_number-40": "assets/question_numbers/40.svg",
            "question_number-41": "assets/question_numbers/41.svg",
            "question_number-42": "assets/question_numbers/42.svg",
            "question_number-43": "assets/question_numbers/43.svg",
            "question_number-44": "assets/question_numbers/44.svg",
            "question_number-45": "assets/question_numbers/45.svg",
            "question_number-46": "assets/question_numbers/46.svg",
            "question_number-47": "assets/question_numbers/47.svg",
            "question_number-48": "assets/question_numbers/48.svg",
            "question_number-49": "assets/question_numbers/49.svg",
            "question_number-50": "assets/question_numbers/50.svg",
            "question_number-51": "assets/question_numbers/51.svg",
            "question_number-52": "assets/question_numbers/52.svg",
            "question_number-53": "assets/question_numbers/53.svg",
            "question_number-54": "assets/question_numbers/54.svg",
            "question_number-55": "assets/question_numbers/55.svg",
            "question_number-56": "assets/question_numbers/56.svg",
            "question_number-57": "assets/question_numbers/57.svg",
            "question_number-58": "assets/question_numbers/58.svg",
            "question_number-59": "assets/question_numbers/59.svg",
            "question_number-60": "assets/question_numbers/60.svg",
            "question_number-61": "assets/question_numbers/61.svg",
            "question_number-62": "assets/question_numbers/62.svg",
            "question_number-63": "assets/question_numbers/63.svg",
            "question_number-64": "assets/question_numbers/64.svg",
            "question_number-65": "assets/question_numbers/65.svg",
            "question_number-66": "assets/question_numbers/66.svg",
            "question_number-67-circle": "assets/question_numbers/67-circle.svg",
            "question_number-68": "assets/question_numbers/68.svg",
            "question_number-69": "assets/question_numbers/69.svg",
            "question_number-70": "assets/question_numbers/70.svg",

            "button-next": "assets/game/button-next.svg",
            "button-next-p": "assets/game/button-next-p.svg",

            "36:element-base": "assets/36/element-base.svg",
            "36:element-outline": "assets/36/element-outline.svg",

            "37:drum": "assets/37/drum.svg",
            "37:cymbal": "assets/37/cymbal.svg",
            "37:guitar": "assets/37/guitar.svg",
            "37:trumpet": "assets/37/trumpet.svg",
            "37:triangle": "assets/37/triangle.svg",

            "40:background": "assets/40/background.svg",
            "40:tip": "assets/40/tip.svg",
            "40:red_frame": "assets/40/wrong_frame.svg",

            "40:string-0": "assets/40/string-0.svg",
            "40:string-1": "assets/40/string-1.svg",
            "40:string-2": "assets/40/string-2.svg",
            "40:string-3": "assets/40/string-3.svg",
            "40:string-4": "assets/40/string-4.svg",
            "40:string-5": "assets/40/string-5.svg",
            "40:string-6": "assets/40/string-6.svg",
            "40:string-7": "assets/40/string-7.svg",

            "40:red": "assets/40/red.svg",
            "40:orange": "assets/40/orange.svg",
            "40:yellow": "assets/40/yellow.svg",
            "40:green": "assets/40/green.svg",
            "40:light_blue": "assets/40/light_blue.svg",
            "40:blue": "assets/40/blue.svg",
            "40:purple": "assets/40/purple.svg",
            "40:white": "assets/40/white.svg",

            "44:begin_point": "assets/44/begin_point.svg",
            "44:begin_text": "assets/44/begin_text.svg",
            "44:maze_room": "assets/44/maze_room.svg",
            "44:maze_spinner": "assets/44/maze_spinner.svg",
            "44:maze_text": "assets/44/maze_text.svg",

            "45:chest-closed": "assets/45/chest-closed.svg",
            "45:chest-open": "assets/45/chest-open.svg",
            "45:chest-open_with_treasure": "assets/45/chest-open_with_treasure.svg",
            "45:text-1": "assets/45/text-1.svg",

            "48:button": "assets/48/button.svg",
            "48:button-p": "assets/48/button-p.svg",
            "48:green_paint_bucket": "assets/48/green_paint_bucket.svg",
            "48:gray_paint_bucket": "assets/48/gray_paint_bucket.svg",
            "48:brown_paint_bucket": "assets/48/brown_paint_bucket.svg",

            "49:schoolbag-closed": "assets/49/schoolbag-closed.svg",
            "49:schoolbag-1-open": "assets/49/schoolbag-1-open.svg",
            "49:schoolbag-2-empty": "assets/49/schoolbag-2-empty.svg",
            "49:schoolbag-2-full": "assets/49/schoolbag-2-full.svg",
            "49:airpods": "assets/49/airpods.svg",
            "49:charger": "assets/49/charger.svg",
            "49:pen": "assets/49/pen.svg",
            "49:textbook-1": "assets/49/textbook-1.svg",
            "49:textbook-2": "assets/49/textbook-2.svg",
            "49:textbook-3": "assets/49/textbook-3.svg",
            "49:textbook-4": "assets/49/textbook-4.svg",
            "49:exercise_book-1": "assets/49/exercise_book-1.svg",
            "49:exercise_book-2": "assets/49/exercise_book-2.svg",
            "49:exercise_book-3": "assets/49/exercise_book-3.svg",
            "49:exercise_book-4": "assets/49/exercise_book-4.svg",
            "49:subject-1": "assets/49/subject-1.svg",
            "49:subject-2": "assets/49/subject-2.svg",
            "49:subject-3": "assets/49/subject-3.svg",
            "49:subject-4": "assets/49/subject-4.svg",

            "51:note": "assets/51/note.svg",
            "51:bean": "assets/51/bean.svg",
            "51:word-1": "assets/51/word-1.svg",
            "51:word-2": "assets/51/word-2.svg",

            "53:draggable_item": "assets/53/draggable_item.svg",
            "53:draggable_item-p": "assets/53/draggable_item-p.svg",
            "53:label-1": "assets/53/label-1.svg",
            "53:label-2": "assets/53/label-2.svg",
            "53:label-3": "assets/53/label-3.svg",
            "53:label-4": "assets/53/label-4.svg",
            "53:label-5": "assets/53/label-5.svg",
            "53:label-6": "assets/53/label-6.svg",

            "55:background": "assets/55/background.svg",

            "60:volleyball-1": "assets/60/volleyball-1.svg",
            "60:volleyball-2": "assets/60/volleyball-2.svg",
            "60:volleyball-3": "assets/60/volleyball-3.svg",
            "60:pump-case": "assets/60/pump-case.svg",
            "60:pump-press": "assets/60/pump-press.svg",

            "63:match": "assets/63/match.svg",

            "68:keyboard_button": "assets/68/keyboard_button.svg",
            "68:keyboard_button-p": "assets/68/keyboard_button-p.svg",
            "68:background": "assets/68/background.svg",
            "68:exercise_book-1": "assets/68/exercise_book-1.svg",
            "68:exercise_book-3": "assets/68/exercise_book-3.svg",
            "68:bottom_cover": "assets/68/bottom_cover.svg",

            "70:button-1": "assets/70/button-1.svg",
            "70:button-2": "assets/70/button-2.svg",
            "70:text-1": "assets/70/text-1.svg",
            "70:text-2": "assets/70/text-2.svg",

            "letter-1": "assets/letters/1.svg",
            "letter-2": "assets/letters/2.svg",
            "letter-3": "assets/letters/3.svg",
            "letter-4": "assets/letters/4.svg",
            "letter-5": "assets/letters/5.svg",
            "letter-6": "assets/letters/6.svg",
            "letter-7": "assets/letters/7.svg",
            "letter-8": "assets/letters/8.svg",
            "letter-9": "assets/letters/9.svg",
            "letter-10": "assets/letters/10.svg",
            "letter-11": "assets/letters/11.svg",
            "letter-12": "assets/letters/12.svg",
            "letter-13": "assets/letters/13.svg",
            "letter-14": "assets/letters/14.svg",
            "letter-15": "assets/letters/15.svg",
            "letter-16": "assets/letters/16.svg",
            "letter-17": "assets/letters/17.svg",
            "letter-18": "assets/letters/18.svg",
            "letter-19": "assets/letters/19.svg",
            "letter-20": "assets/letters/20.svg",
            "letter-21": "assets/letters/21.svg",
            "letter-22": "assets/letters/22.svg",
            "letter-23": "assets/letters/23.svg",
            "letter-24": "assets/letters/24.svg",
            "letter-25": "assets/letters/25.svg",
            "letter-26": "assets/letters/26.svg",
            "letter-27": "assets/letters/27.svg",
            "letter-28": "assets/letters/28.svg",
            "letter-29": "assets/letters/29.svg",
            "letter-30": "assets/letters/30.svg",
            "letter-31": "assets/letters/31.svg",
            "letter-32": "assets/letters/32.svg",

            "menus:game_complete_poster": "assets/menus/game_complete_poster.svg"
        },
        audio: {
            "menus:wind": "assets/sounds/menus-wind.wav",

            "40:start_game": "assets/sounds/40-start_game.wav",
            "40:correct": "assets/sounds/40-correct.wav",
            "45:open": "assets/sounds/45-open.wav",
            "45:close": "assets/sounds/45-close.wav",
            "45:treasure": "assets/sounds/45-treasure.wav",
            "49:zipper": "assets/sounds/49-zipper.wav",
            "49:wool": "assets/sounds/49-wool.wav",
            "50:arrow-let-go": "assets/sounds/50-arrow_let_go.wav",

            "51:piano-F": "assets/sounds/51-piano-F.wav",
            "51:piano-G": "assets/sounds/51-piano-G.wav",
            "60:inflate": "assets/sounds/60-inflate.wav",
            "68:write": "assets/sounds/68-write.wav",

            "beep": "assets/sounds/beep.wav",
            "ding": "assets/sounds/ding.wav",
            "explosion": "assets/sounds/explosion.wav",
            "game_over": "assets/sounds/game_over.wav",
            "pew": "assets/sounds/pew.wav",
            "tick": "assets/sounds/tick.wav",

            "game_complete": "assets/sounds/game_complete.wav"
        },
        masks: [
            "37:drum",
            "37:cymbal",
            "37:guitar",
            "37:trumpet",
            "37:triangle",
            "45:chest-closed",
            "button-next",
            "44:maze_collision",
            "44:maze_spinner_collision"
        ],
        nearestFilterImages: [],
        audioVolumeNodes: [],
    }
};