import * as PIXI from "pixi.js";
import * as F from "@/core/functions";
import { Msg, settings } from "@/editable";
import { dp, m, messages } from "@/core/sensing_properties";
import { Sprite, TopSprite, TopContainer, CompHitbox, CompMask, CompGroup, HitboxParameters, MaskParameters } from "@/core/core";

import { AnimationSequence } from "@/custom";
import * as C from "@/custom";
import { soundManager } from "@/core/sound_manager";
import { g } from "./global_properties";
import { s } from "./storage";


// QUESTION 50 (don't touch)
export class SArrowLevel extends TopContainer {
    readonly GRID_WIDTH = 7;
    readonly GRID_HEIGHT = 7;
    escapedArrows = 0;

    grid!: Uint8Array;
    constructor() {
        super();

        // pick random level
        this.createLevel([
            "0823160939981923313331915111122122721639290898130",
            "0931160233293619127152116921311111239582290929270",
            "0211190573113539189119322131112336171261920996390",
            "0963130893292359292613121821299231123227330773190"
        ][F.randomNumber(0, 3)]);
    }


    createLevel(levelCode: string) {
        // fill the grid from the level code
        this.grid = new Uint8Array(this.GRID_WIDTH*this.GRID_HEIGHT);
        for (let i = 0; i < this.grid.length; i++) {
            this.grid[i] = parseInt(levelCode[i], 10);
        }

        // apply grid transformation randomly
        if (F.randomNumber(0, 1)) this.mirrorHorizontal();
        if (F.randomNumber(0, 1)) this.mirrorVertical();
        if (F.randomNumber(0, 1)) this.rotate90();


        // decoration
        {
            const g = new PIXI.Graphics();
            for (let i = 0; i < this.grid.length; i++) {
                if (this.grid[i]!==0) {
                    const x = (settings.SCREEN_WIDTH-((this.GRID_WIDTH-1) * CArrow.SIZE))/2 + ((i%this.GRID_WIDTH) * CArrow.SIZE);
                    const y = (settings.SCREEN_HEIGHT-((this.GRID_HEIGHT-1) * CArrow.SIZE))/2 + (Math.floor(i/this.GRID_WIDTH) * CArrow.SIZE) - 10;
                    g.circle(x, y, 3);
                }
            }
            g.fill("#e0e0e0");
            this.addChild(g);
        }


        // then create arrows
        for (let i = 0; i < this.grid.length; i++) {
            if (SArrowLevel.isPoint(this.grid[i])) {
                this.addChild(new CArrow(this, i, SArrowLevel.convertToDirection(this.grid[i])));
            }
        }
    }

    static isPoint(number: number) {
        return number >= 5 && number <= 8;
    }
    static convertToDirection(number: number): number {
        return number-5;
    }
    static convertDirectionToXY(direction: number, multiplier: number) {
        if (direction===0) { // up
            return {x: 0, y: -multiplier};
        }
        else if (direction===2) { // down
            return {x: 0, y: multiplier};
        }
        else if (direction===3) { // left
            return {x: -multiplier, y: 0};
        }
        else { // right
            return {x: multiplier, y: 0};
        }
    }
    static oppositeDirection(direction: number): number {
        return F.remainder(direction+2, 4);
    }

    mirrorHorizontal() {
        // BELOW CODE GENERATED BY AI
        for (let i = 0; i < this.grid.length; i += this.GRID_WIDTH) {
            this.grid.subarray(i, i + this.GRID_WIDTH).reverse();
        }
        
        // change data
        for (let i = 0; i < this.grid.length; i++) {
            const number = this.grid[i];
            if (number === 6) { // right-left
                this.grid[i] = 8;
            }
            else if (number === 8) { // left-right
                this.grid[i] = 6;
            }
            else if (number === 2) { // turn right-turn left
                this.grid[i] = 3;
            }
            else if (number === 3) { // turn left-turn right
                this.grid[i] = 2;
            }
        }
    }
    mirrorVertical() {
        // BELOW CODE GENERATED BY AI
        const result = new Uint8Array(this.GRID_WIDTH*this.GRID_HEIGHT);

        for (let y = 0; y < this.GRID_HEIGHT; y++) {
            const sourceRow = this.grid.subarray(y * this.GRID_WIDTH, (y + 1) * this.GRID_WIDTH);
            result.set(sourceRow, (this.GRID_HEIGHT - 1 - y) * this.GRID_WIDTH);
        }

        this.grid = result;

        // change data
        for (let i = 0; i < this.grid.length; i++) {
            const number = this.grid[i];
            if (number === 5) { // up-down
                this.grid[i] = 7;
            }
            else if (number === 7) { // down-up
                this.grid[i] = 5;
            }
            else if (number === 2) { // turn right-turn left
                this.grid[i] = 3;
            }
            else if (number === 3) { // turn left-turn right
                this.grid[i] = 2;
            }
        }
    }
    rotate90() {
        // BELOW CODE GENERATED BY AI
        const result = new Uint8Array(this.GRID_WIDTH*this.GRID_HEIGHT);

        for (let y = 0; y < this.GRID_HEIGHT; y++) {
            for (let x = 0; x < this.GRID_WIDTH; x++) {
                // source index
                const oldIndex = y * this.GRID_WIDTH + x;
                
                // new coordinates after rotation
                const newX = (this.GRID_HEIGHT - 1) - y;
                const newY = x;
                
                // new index
                const newIndex = newY * this.GRID_HEIGHT + newX;
                
                result[newIndex] = this.grid[oldIndex];
            }
        }

        this.grid = result;

        // change data
        for (let i = 0; i < this.grid.length; i++) {
            const number = this.grid[i];
            if (SArrowLevel.isPoint(number)) { // rotate direction by 90
                this.grid[i] = F.remainder((number - 5)+1, 4) + 5;
            }
        }
    }

    messageStep(message: Msg) {
        switch (message) {
            case Msg.TICK_GAME_LOGIC:
                (this.children).forEach((sp)=>{
                    if (sp instanceof CArrow) {
                        sp.tick();
                    }
                });
                break;
        }
    }
}
class CArrow extends PIXI.Container {
    static readonly SIZE = 32;

    g: PIXI.Graphics;
    i;
    endDirection: number;
    trail: number[];

    private collidableGroup = new CompGroup(this);

    private reachDistance = 0;
    private offset = 0;
    private animState: "idle"|"going"|"goingBack" = "idle";
    private animLifetimeOffset = 0;
    private animLifetimeColor = 0;
    private animColor = "#404850";

    private isLastArrow = false;

    constructor(readonly p: SArrowLevel, i: number, endDirection: number) {
        super();

        this.i = i;
        this.endDirection = endDirection;
        const col = i%this.p.GRID_WIDTH;
        const row = Math.floor(i/this.p.GRID_WIDTH);

        this.trail = [];
        {
            let movingI = this.i;
            let movingDirection = SArrowLevel.oppositeDirection(this.endDirection);

            while (true) {
                movingI = this.moveI(movingI, movingDirection);

                let data = this.p.grid[movingI]; // data may be turn, start or end
                if (data===0 || data > 3) { 
                    break; // exit the loop
                }
                
                this.trail.push(data);

                if (data===2) {
                    // turn right
                    movingDirection = F.remainder(movingDirection+1, 4);
                }
                if (data===3) {
                    // turn left
                    movingDirection = F.remainder(movingDirection-1, 4);
                }
            }
        }


        this.g = new PIXI.Graphics();
        
        this.position.set(
            (settings.SCREEN_WIDTH-((this.p.GRID_WIDTH-1) * CArrow.SIZE))/2 + (col * CArrow.SIZE),
            (settings.SCREEN_HEIGHT-((this.p.GRID_HEIGHT-1) * CArrow.SIZE))/2 + (row * CArrow.SIZE) - 10
        )
        
        this.addChild(this.g);

        this.drawTrail(0, true);
    }

    
    moveI(currentI: number, direction: number) {
        if (direction === 0) { // up
            currentI -= this.p.GRID_WIDTH;
            if (currentI < 0) {
                return -1;
            }
        }
        else if (direction === 2) { // down
            currentI += this.p.GRID_WIDTH;
            if (currentI >= this.p.GRID_WIDTH*this.p.GRID_HEIGHT) {
                return -1;
            }
        }
        else if (direction === 3) { // left
            currentI -= 1;
            if (F.remainder(currentI, this.p.GRID_WIDTH) === this.p.GRID_WIDTH-1) {
                return -1;
            }
        }
        else if (direction === 1) { // right
            currentI += 1;
            if (F.remainder(currentI, this.p.GRID_WIDTH) === 0) {
                return -1;
            }
        }
        return currentI;
    }
    drawTrail(offset: number, needToCreateHitboxes=false) {
        let movingDirection = SArrowLevel.oppositeDirection(this.endDirection);

        const offsetXY = SArrowLevel.convertDirectionToXY(this.endDirection, offset*CArrow.SIZE);
        
        const drawLine = ()=>{
            if (remainingLength>0) {
                const linePiece = CArrow.SIZE * Math.min(remainingLength, 1);

                if (movingDirection===0) { // up
                    penY -= linePiece;
                }
                else if (movingDirection===2) { // down
                    penY += linePiece;
                }
                else if (movingDirection===3) { // left
                    penX -= linePiece;
                }
                else if (movingDirection===1) { // right
                    penX += linePiece;
                }
                this.g.lineTo(penX, penY);
                remainingLength--;

                // create child hitbox
                if (needToCreateHitboxes) this.collidableGroup.group.push(new CompHitbox(this, {offsetX: penX-CArrow.SIZE/2, offsetY: penY-CArrow.SIZE/2, width: CArrow.SIZE, height: CArrow.SIZE}));
            }
        };
        
        let remainingLength = (this.trail.length+1)-offset;
        
        let penX = (this.endDirection===3) 
            ? Math.min(remainingLength*CArrow.SIZE, 0)
            : (this.endDirection===1)
            ? Math.max(-remainingLength*CArrow.SIZE, 0)
            : 0;
        let penY = (this.endDirection===0) 
            ? Math.min(remainingLength*CArrow.SIZE, 0)
            : (this.endDirection===2)
            ? Math.max(-remainingLength*CArrow.SIZE, 0)
            : 0;

        // if the butt is outside the screen, destroy this object
        if (this.x+penX < 0 
            || this.x+penX > settings.SCREEN_WIDTH
            || this.y+penY < 0 
            || this.y+penY > settings.SCREEN_HEIGHT
        )
        {
            this.destroyItself();
            return;
        }


        this.g.clear();
        // arrow
        this.g
            .rotateTransform(this.endDirection*Math.PI/2)
            .translateTransform(offsetXY.x, offsetXY.y)
            .poly([0,-8, -8,8, 8,8], true)
            .fill(this.animColor)
            .stroke({color: this.animColor,width:4,join:"round"})
            .resetTransform();
        // trail
        this.g.moveTo(offsetXY.x, offsetXY.y);
        this.g.lineTo(penX, penY);
        if (needToCreateHitboxes) this.collidableGroup.group.push(new CompHitbox(this, {offsetX: penX-CArrow.SIZE/2, offsetY: penY-CArrow.SIZE/2, width: CArrow.SIZE, height: CArrow.SIZE}));

        if (!(remainingLength<=0)) {
            drawLine();
            for (let turn of this.trail) {
                if (remainingLength<=0) {
                    break;
                }

                if (turn===2) {
                    // turn right
                    movingDirection = F.remainder(movingDirection+1, 4);
                }
                else if (turn===3) {
                    // turn left
                    movingDirection = F.remainder(movingDirection-1, 4);
                }

                drawLine();
            }
        }
        // stroke
        this.g.stroke({color: this.animColor, width: 6, join: "round", cap: "round"});
    }
    destroyItself() {
        if (this.isLastArrow) {
            s.main.nextQuestion();
        }
        this.destroy(true);
    }

    freeDataOnGrid() {
        let movingI = this.i;
        let movingDirection = SArrowLevel.oppositeDirection(this.endDirection);
        
        this.p.grid[movingI] = 0;
        for (let turn of this.trail) {
            movingI = this.moveI(movingI, movingDirection);
            this.p.grid[movingI] = 0;


            if (turn===2) {
                // turn right
                movingDirection = F.remainder(movingDirection+1, 4);
            }
            if (turn===3) {
                // turn left
                movingDirection = F.remainder(movingDirection-1, 4);
            }
        }
        movingI = this.moveI(movingI, movingDirection);

        this.p.grid[movingI] = 0;
    }

    tick() {
        // if an arrow is clicked
        if (this.collidableGroup.collidePointer(0) && m.pointerIsPressed(0) && this.animState==="idle") {
            this.launchArrow();
        }

        let finalRefresh = false;

        // offset tick
        if (this.animState==="going") {
            this.offset += 15 * m.delta;
            if (this.offset > this.reachDistance && this.reachDistance !== 0) {
                s.main.loseLife();
                s.main.invulnerability = 0;

                this.animState = "goingBack";
                this.animLifetimeOffset = 0.3;
                this.animLifetimeColor = 0.5;
            }
        }
        if (this.animState==="goingBack") {
            this.animLifetimeOffset -= m.delta;
            if (this.animLifetimeOffset <= 0) {
                this.animLifetimeOffset = 0;
                this.animState = "idle";
                finalRefresh = true;
            }

            this.offset = F.scale(F.ease(this.animLifetimeOffset/0.3, "cubicIn"), 1, 0, this.reachDistance, 0);
        }

        // color tick
        if (this.animLifetimeColor > 0) {
            this.animLifetimeColor -= m.delta;
            if (this.animLifetimeColor <= 0) {
                this.animLifetimeColor = 0;
                finalRefresh = true;
            }

            this.animColor = C.getColorFromGradient(["#404850", "#ff0000", "#404850"], F.scale(this.animLifetimeColor, 0.5, 0, 0, 1));
        }

        // animation tick
        if (this.animState!=="idle" || this.animLifetimeColor > 0 || finalRefresh) {
            // it can also destroy itself when it is off screen
            this.drawTrail(this.offset);
        }
    }

    launchArrow() {
        let movingI = this.i;
        let distance = 1;
        let canEscape = false;

        while (true) {
            movingI = this.moveI(movingI, this.endDirection);

            // if the arrow can leave boundary
            if (movingI===-1) {
                canEscape = true;
                break;
            }
            // check for obstacles
            if (this.p.grid[movingI]!==0) {
                break;
            }
            // keep going
            distance++;
        }
        if (!canEscape) {
            this.reachDistance = distance-0.2;
        }
        else {
            this.reachDistance = 0;

            this.p.escapedArrows++;
            if (this.p.escapedArrows === 8) {
                this.isLastArrow = true;
                s.main.gameTick = false;
            }
            this.freeDataOnGrid();
            soundManager.produce("50:arrow-let-go");
        }

        this.animState = "going";
    }

}
